# SPDX-FileCopyrightText: Copyright (c) 2023 - 2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# OneCycleLR scheduler — PanguPlasimLegacy default
# (PanguWeather v2.0 PANGU_PLASIM_H5_DERECHO_0514).

optimizer_type: AdamW
lr: 1.0e-4
weight_decay: 3.0e-6

scheduler: OneCycleLR
oc_pct_start: 0.1
oc_div_factor: 1.0e5
oc_final_div_factor: 0.00025
