#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2023 - 2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: Copyright (c) 2026 The University of Chicago.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Render the pinned dependency closure for the ai-rossby container image.
#
# Why an export rather than `uv pip install .`:
#   uv.lock already backs every cluster venv (see hpc/scripts/sync-all-clusters.sh),
#   so exporting it guarantees the image's dep set is identical to what the venvs
#   resolve today, with one source of truth. `--no-emit-project` keeps physicsnemo
#   itself out — the repo checkout is bind-mounted at run time, not baked in.
#
# Why torch is stripped:
#   The NGC base image ships torch 2.10.0a0 plus a matched CUDA/cuDNN/NCCL
#   userland, and its apex / transformer-engine / torch-tensorrt C extensions are
#   compiled against that exact build. Note 2.10.0a0 < 2.10.0 under PEP 440, so
#   the `torch>=2.10.0,<2.11.0` pin in pyproject.toml does NOT consider NGC's
#   torch acceptable and a plain install silently replaces it with the PyPI wheel
#   — the same shadowing failure documented in hpc/deltaai.md:74. We therefore
#   drop torch, torchvision, triton and torch's private nvidia-* CUDA wheels and
#   let the base image provide them.
#
# Why no cu12/cu129/cu13 extra:
#   Those extras add only torch/torchvision (supplied by the base image) plus
#   cuml, pylibraft, cupy and DALI. cuml/pylibraft/cupy have zero imports in
#   physicsnemo/ or test/, and every DALI import is OptionalImport-guarded, so
#   none of them are reachable from the ai-rossby or ai-rossbypalooza recipes.
#   Dropping the extra is what removes the per-cluster CUDA-variant split.
set -euo pipefail

OUT="${1:?usage: make_requirements.sh <output-requirements.txt>}"
REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"

# nvidia-* distributions we expect to be torch-owned and therefore strippable.
# Verified against `uv export`'s own `# via` annotations. If the lock introduces
# an nvidia-* wheel that is NOT in this list, the guard below fails the build
# rather than silently deleting something a live dependency needs (e.g. DALI's
# nvidia-nvimgcodec / nvidia-libnvcomp, if the DALI extra is ever restored).
TORCH_OWNED_NVIDIA_RE='^nvidia-(cublas|cuda-cccl|cuda-crt|cuda-cupti|cuda-nvcc|cuda-nvrtc|cuda-runtime|cudnn|cufft|cufile|curand|cusolver|cusparse|cusparselt|nccl|nvjitlink|nvshmem|nvtx|nvvm)(-cu1[23])?=='

cd "$REPO_ROOT"

raw="$(mktemp)"; trap 'rm -f "$raw"' EXIT
uv export --frozen --no-emit-project --no-hashes --no-annotate --no-header \
    --extra sfno-extras \
    --extra utils-extras \
    --extra datapipes-extras \
    --extra muon-optimizers \
    --group dev \
    --python 3.12 \
    -o "$raw" >/dev/null

# Guard: every nvidia-* in the closure must be a known torch-owned one.
if unexpected="$(grep -E '^nvidia-' "$raw" | grep -Ev "$TORCH_OWNED_NVIDIA_RE" || true)"; then
    if [ -n "$unexpected" ]; then
        echo "ERROR: unrecognised nvidia-* distribution(s) in the lock closure:" >&2
        echo "$unexpected" | sed 's/^/  /' >&2
        echo "Re-check ownership with \`uv export\`'s '# via' annotations, then either" >&2
        echo "add it to TORCH_OWNED_NVIDIA_RE (torch-owned) or leave it installed." >&2
        exit 1
    fi
fi

{
    echo "# Generated by hpc/containers/make_requirements.sh — do not edit."
    echo "# torch/torchvision/triton and torch's nvidia-* CUDA wheels come from the"
    echo "# NGC base image; see that script's header for why."
    grep -Ev "^(torch|torchvision|triton)==" "$raw" | grep -Ev "$TORCH_OWNED_NVIDIA_RE"
} > "$OUT"

kept="$(grep -cE '^[a-zA-Z0-9]' "$OUT")"
dropped="$(( $(grep -cE '^[a-zA-Z0-9]' "$raw") - kept ))"
echo "make_requirements: ${kept} packages kept, ${dropped} base-image-provided packages dropped -> $OUT"
